export const wordsfromdatabase = {
    3: [
      'DOG', 'CAT', 'BAT', 'MAP', 'SUN', 'CAR', 'PEN', 'FOX', 'RAT', 'LOG',
      'TOY', 'CUP', 'NUT', 'JAR', 'FISH', 'FAN', 'MUD', 'SKY', 'ICE', 'CUP',
      'BAT', 'BOX', 'JET', 'BAG', 'RED', 'LEG', 'PIG', 'COW', 'RAT', 'MAT',
      'ZIP', 'NET', 'ROW', 'HAM', 'TAP', 'WEB', 'OAK', 'DOG', 'LOG', 'ARM',
      'MUD', 'FOX', 'DOG', 'CAT', 'SUN', 'HAT', 'MAP', 'HOT', 'CUP', 'KEY',
      'BOW', 'CAR', 'BAT', 'PEG', 'LEG', 'FAN', 'BAG', 'PEN', 'ICE', 'LOG',
      'COT', 'JET', 'OWL', 'BEE', 'CUP', 'NUT', 'SKY', 'CAT', 'DOG', 'RAT'
    ],
    4: [
      'MOON', 'TREE', 'FISH', 'BIRD', 'FROG', 'STAR', 'SHIP', 'LAKE', 'SAND', 'WIND',
      'RING', 'ROSE', 'HILL', 'PATH', 'BALL', 'DOOR', 'BALL', 'WOLF', 'DEER', 'WAVE',
      'FIRE', 'SHIP', 'SHOE', 'TENT', 'KITE', 'CAKE', 'DOVE', 'COIN', 'PALM', 'CAMP',
      'PARK', 'BALL', 'FLAG', 'MAZE', 'NEST', 'TIDE', 'WOOD', 'BEAM', 'WAVE', 'LEAF',
      'SAND', 'ZONE', 'FROG', 'MOON', 'STAR', 'WIND', 'SNOW', 'DUST', 'GOLD', 'OAK',
      'BLUE', 'WOLF', 'TIDE', 'WIND', 'CAMP', 'CAKE', 'MAZE', 'BEAM', 'LEAF', 'ROSE',
      'SNOW', 'WAVE', 'ZONE', 'SHIP', 'WOLF', 'PATH', 'KITE', 'WOOD', 'LAKE', 'COIN'
    ],
    5: [
      'APPLE', 'TIGER', 'HORSE', 'CAMEL', 'SNAKE', 'CLOUD', 'STONE', 'CHAIR', 'DREAM', 'TABLE',
      'OCEAN', 'RIVER', 'NIGHT', 'BRAVE', 'FIELD', 'GROUP', 'LIGHT', 'MAGIC', 'PEACE', 'VIVID',
      'EARTH', 'WATER', 'CRANE', 'BISON', 'FROST', 'GRAPE', 'TIGER', 'STORM', 'BRIGHT', 'FLYER',
      'SHOES', 'GRAPE', 'WORLD', 'CRAZY', 'GUITAR', 'BEACH', 'FLAME', 'SHARP', 'CLEAN', 'COAST',
      'ANGLE', 'LASER', 'FLOCK', 'TRAIN', 'LUCKY', 'QUICK', 'STEEL', 'SWARM', 'FLAME', 'DREAM',
      'PIANO', 'SQUID', 'PLANE', 'LUNAR', 'SHADOW', 'SWAMP', 'MOUNT', 'MUSIC', 'CRANE', 'GLORY',
      'GLOVE', 'LIGHT', 'FLAME', 'CHARM', 'QUILT', 'STORM', 'NORTH', 'SOUTH', 'PEARL', 'SPACE'
    ],
    6: [
      'PLANET', 'FOREST', 'DESERT', 'ISLAND', 'CASTLE', 'DRAGON', 'SHADOW', 'MIRROR', 'WINDOW', 'FLOWER',
      'GALAXY', 'VORTEX', 'BRIDGE', 'ISLAND', 'CANYON', 'DIVINE', 'BAMBOO', 'NATURE', 'ROCKET', 'SUNSET',
      'SUNRISE', 'MOONLIGHT', 'PUZZLE', 'HORIZON', 'EXPLORE', 'MYSTIC', 'TEMPLE', 'WHISPER', 'JUNGLE', 'BEACON',
      'ADVENTURE', 'VORTEX', 'CASCADE', 'BUTTERFLY', 'ETHEREAL', 'HOLLOW', 'GOBLIN', 'ORACLE', 'GENIUS', 'PHOTON',
      'PLASMA', 'NEBULA', 'VORTEX', 'PINNACLE', 'ECHO', 'WHISPER', 'SPECTRUM', 'STARLIGHT', 'STREAM', 'GRAVITY',
      'BRIDGE', 'SILVER', 'CREATURE', 'MYSTERY', 'DISTANT', 'DREAMER', 'TWILIGHT', 'GALAXY', 'BEACON', 'JOURNEY',
      'PLASMA', 'SOLAR', 'UNIQUE', 'CANYON', 'WHISPER', 'NEBULA', 'QUARTZ', 'MERMAID', 'DRAGON', 'TEMPLE'
    ],
    7: [
      'SUNRISE', 'SUNSET', 'VOLCANO', 'CANYON', 'TEMPLE', 'PYRAMID', 'DIAMOND', 'EMERALD', 'CRYSTAL', 'RAINBOW',
      'THUNDER', 'TORNADO', 'ICEBERG', 'GRIFFIN', 'WYVERN', 'BANSHEE', 'CHIMERA', 'MERMAID', 'SPHINX', 'CYCLOPS',
      'PHOENIX', 'DOLPHIN', 'HORIZON', 'SAPPHIRE', 'ECLIPSE', 'SUNSHINE', 'JUNGLE', 'TORNADO', 'SHADOW', 'BEACON',
      'ILLUSION', 'QUASAR', 'HARVEST', 'GALAXY', 'INFINITY', 'MYSTERY', 'FOUNTAIN', 'WILDLIFE', 'DRAGONFLY', 'GLACIER',
      'COSMOS', 'FOREST', 'ELEMENT', 'IMPACT', 'RADIANCE', 'MYSTIC', 'QUASAR', 'TEMPEST', 'SUNBEAM', 'WHISPER',
      'STARLIGHT', 'HORIZON', 'SUNRISE', 'SPARKLE', 'HURRICANE', 'TWILIGHT', 'JOURNEY', 'BLIZZARD', 'PHOENIX', 'BEACON',
      'NEPTUNE', 'SAPPHIRE', 'GUARDIAN', 'MIRAGE', 'WILDERNESS', 'DREAMSCAPE', 'AURORA', 'OCEANIC', 'PINNACLE', 'SPARK'
    ],
    8: [
      'MOUNTAIN', 'SAPPHIRE', 'AMETHYST', 'TWILIGHT', 'UNICORN', 'CENTAUR', 'KRAKEN', 'ZEPHYR', 'MINOTAUR', 'CERBERUS',
      'GARGOYLE', 'BASILISK', 'SEAHORSE', 'SCORPION', 'PORCUPINE', 'KANGAROO', 'ELEPHANT', 'GIRAFFE', 'CHEETAH', 'LEOPARD',
      'PANTHER', 'JAGUAR', 'RHINOCEROS', 'HIPPOPOTAMUS', 'ORANGUTAN', 'CHIMPANZEE', 'GORILLA', 'AARDVARK', 'CROCODILE', 'ALLIGATOR',
      'PLATYPUS', 'FLAMINGO', 'HUMMINGBIRD', 'PEACOCK', 'OSTRICH', 'PENGUIN', 'ALBATROSS', 'SPHINX', 'MERMAID', 'CHIMERA',
      'DOLPHIN', 'GIRAFFE', 'TORNADO', 'MOONLIGHT', 'WHIRLPOOL', 'SNOWFALL', 'TEMPEST', 'HORIZON', 'VORTEX', 'MYSTIC',
      'FIREFLY', 'DRAGONFLY', 'EMERALD', 'STORMCLOUD', 'GLOWWORM', 'THUNDERSTORM', 'SANDSTORM', 'GOLDENROD', 'MONSOON', 'SUNBURST',
      'WHISPER', 'MIRAGE', 'TEMPEST', 'UNICORN', 'SPHINX', 'MOUNTAIN', 'TORNADO', 'RAINSTORM', 'LIGHTNING', 'GLACIER',
      'SUNSHINE', 'STORM', 'SHADOW', 'MIST', 'VORTEX', 'STORM', 'MERMAID', 'BASILISK', 'GLOW', 'TORNADO'
    ]
  };
  